name: Download Trudeau Dialog
on:
  schedule:
    # 5pm UTC is 1pm eastern, which should be adequate time for the videos to become available
    - cron:  '10 17 * * *'
  push: {}

jobs:
  trudeau:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: |
        ruby test/test.rb
    - name: Generate Dialog
      run: |
        ruby captions.rb -t "${{ secrets.GOOGLE_TOKEN }}" --force
    - name: Commit Dialog
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all .
        git commit -m "Add new dialog from Trudeau" || true
        remote_repo="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        git push "${remote_repo}" HEAD:${{ github.ref }} --follow-tags
